version: "3.8"

#volumes:
#  shared-data:
#  logs-data:

volumes:
  zkp-circuit-cache: {}

services:
  client1:
    build: .
    container_name: client1
    command: --peer-id client1
    user: "1000:1000"
    environment:
      - ZKP_AUTOPROVE=1
      - ZKP_PTAU_GEN=0                      # ✅ autorise la génération auto du ptau si manquant
      - ZKP_PTAU=/app/shared/zkp/ptau/powersOfTau28_hez_final_18.ptau
      - ZKP_PTAU_POWER=18                   
      - ZKP_CIRCUIT_DIR=/app/zkp/avg_chunk
      - ZKP_CHUNK=4096
      - ZKP_SCALE=1000000
      - NODE_OPTIONS=--max-old-space-size=8192
    volumes:
      - ./shared-data:/app/shared
      - ./logs-data:/app/logs
      - ./certificates:/app/certs
      - ./commits:/app/commits
      - zkp-circuit-cache:/app/zkp

  client2:
    build: .
    container_name: client2
    command: --peer-id client2
    user: "1000:1000"
    environment:
      - ZKP_AUTOPROVE=1
      - ZKP_PTAU_GEN=0                      # ✅ autorise la génération auto du ptau si manquant
      - ZKP_PTAU=/app/shared/zkp/ptau/powersOfTau28_hez_final_18.ptau
      - ZKP_PTAU_POWER=18                  
      - ZKP_CIRCUIT_DIR=/app/zkp/avg_chunk
      - ZKP_CHUNK=4096
      - ZKP_SCALE=1000000
      - NODE_OPTIONS=--max-old-space-size=8192
    volumes:
      - ./shared-data:/app/shared
      - ./logs-data:/app/logs
      - ./certificates:/app/certs
      - ./commits:/app/commits
      - zkp-circuit-cache:/app/zkp

  client3:
    build: .
    container_name: client3
    command: --peer-id client3
    user: "1000:1000"
    environment:
      - ZKP_AUTOPROVE=1
      - ZKP_PTAU_GEN=0                      # ✅ autorise la génération auto du ptau si manquant
      - ZKP_PTAU=/app/shared/zkp/ptau/powersOfTau28_hez_final_18.ptau
      - ZKP_PTAU_POWER=18                   
      - ZKP_CIRCUIT_DIR=/app/zkp/avg_chunk
      - ZKP_CHUNK=4096
      - ZKP_SCALE=1000000
      - NODE_OPTIONS=--max-old-space-size=8192
    volumes:
      - ./shared-data:/app/shared
      - ./logs-data:/app/logs
      - ./certificates:/app/certs
      - ./commits:/app/commits
      - zkp-circuit-cache:/app/zkp
